### ISSUE TITLE
兄弟为啥会秒退啊，一运行打开浏览器就秒退报错

### ISSUE THREAD

**Issue by Hbzz** [jhcoco/bosszp-selenium#2]
PS D:\vs\bosszz\bosszp-selenium-master\bosszp-selenium-master> & C:/Users/zhangzhen/AppData/Local/Programs/Python/Python312/python.exe d:/vs/bosszz/bosszp-selenium-master/bosszp-selenium-master/boss_selenium.py

DevTools listening on ws://127.0.0.1:54584/devtools/browser/296ffe6a-eff7-4087-9910-491e788dd06a
[9000:29248:0812/164917.227:ERROR:edge_qqbrowser_importer_utils_win.cc(126)] QQBrowser user data path not found.
[9000:31488:0812/164918.215:ERROR:fallback_task_provider.cc(127)] Every renderer should have at least one task provided by a 
primary task provider. If a "Renderer" fallback task is shown, it is a bug. If you have repro steps, please file a new bug and tag it as a dependency of crbug.com/739782.
2024-08-12正在抓取后端开发--Java
Traceback (most recent call last):
  File "d:\vs\bosszz\bosszp-selenium-master\bosszp-selenium-master\boss_selenium.py", line 80, in <module>
    browser.find_elements(by=By.XPATH, value='//*[@id="main"]/div/div[1]/div/div[1]/dl[1]/div/ul/li/div/a')[i].click()
  File "C:\Users\zhangzhen\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\zhangzhen\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhangzhen\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\zhangzhen\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <a ka="search_100101" href="/c100010000-p100101/">...</a> is not clickable at point (13, 9). Other element would receive the click: <div id="header">...</div>
  (Session info: MicrosoftEdge=127.0.2651.98)
Stacktrace:
        GetHandleVerifier [0x00007FF7C9CE05F2+11762]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7C9C80939+271465]
        (No symbol) [0x00007FF7C9A9FE6E]
        (No symbol) [0x00007FF7C9AECD43]
        (No symbol) [0x00007FF7C9AEAFF4]
        (No symbol) [0x00007FF7C9AE8D60]
        (No symbol) [0x00007FF7C9AE7DA1]
        (No symbol) [0x00007FF7C9ADCA4C]
        (No symbol) [0x00007FF7C9B05F3A]
        (No symbol) [0x00007FF7C9ADC2FD]
        (No symbol) [0x00007FF7C9ADC1CD]
        (No symbol) [0x00007FF7C9B06220]
        (No symbol) [0x00007FF7C9ADC2FD]
        (No symbol) [0x00007FF7C9B1FA97]
        (No symbol) [0x00007FF7C9B05BA3]
        (No symbol) [0x00007FF7C9ADB80C]
        (No symbol) [0x00007FF7C9ADACED]
        (No symbol) [0x00007FF7C9ADB3D1]
        Microsoft::Applications::Events::EventProperty::empty [0x00007FF7C9E5B574+879700]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7C9C15D5F+56159]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7C9C086F3+1267]
        Microsoft::Applications::Events::EventProperty::empty [0x00007FF7C9E5A2CD+874925]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7C9C88531+303201]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7C9C848F4+287780]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7C9C84A2B+288091]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7C9C7C980+255152]
        BaseThreadInitThunk [0x00007FF9B9917374+20]
        RtlUserThreadStart [0x00007FF9BA89CC91+33]

**Comment by jhcoco** [comment]
程序运行过程中，不要移动鼠标，会导致聚焦异常，悬浮框消失导致程序错误
